server:
  port: 8040
spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: 117.50.105.135:15098
    gateway:
      discovery:
        locator:
          # 让gateway通过服务发现组件找到其它的微服务
          enabled: true
      routes:
        - id: user_route
          uri: lb://user-center
          predicates:
            - Path=/users/**
        - id: content_route
          uri: lb://content-center
          predicates:
            - Path=/shares/**,/admin/shares/**
  zipkin:
    base-url: http://localhost:9411
  #  discoveryClientEnabled: false   #如果有报nacos异常，spring cloud把上述地址当作服务发现地址的话，可以这样解决
  sleuth:
    sampler:
      # 抽样率，默认0.1 （10%） [只有10%的数据会上报到zipkin，90%的数据会被丢弃]
      probability: 1.0
# actuator
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
